CREATE OR REPLACE TRIGGER boostBuyer
AFTER INSERT ON Sale
FOR EACH ROW
BEGIN
  UPDATE Buyer
  SET PURCHASESYEARTODATE = 
    CASE 
      WHEN PURCHASESYEARTODATE IS NULL THEN :NEW.salePrice
      ELSE PURCHASESYEARTODATE + :NEW.salePrice
    END
  WHERE buyerId = :NEW.buyerId;
END;
/ 